/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ppe3;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author FIGUERES Adrien
 */
public class Formulaire extends javax.swing.JPanel {

    //Connection connexion;
    BddSQL bdd = new BddSQL();
    DaoSIO monDao = DaoSIO.getInstance();
    
    /**
     * Creates new form Formulaire
     */
    public Formulaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsernameLogging = new javax.swing.JTextField();
        jButtonLogging = new javax.swing.JButton();
        jLabelEtatConnexion = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();

        jLabel1.setText("Username :");

        jLabel2.setText("Password :");

        jTextFieldUsernameLogging.setText("Adriraxor");

        jButtonLogging.setText("Connexion");
        jButtonLogging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoggingActionPerformed(evt);
            }
        });

        jLabelEtatConnexion.setText("Non Connecter");

        jLabelTitle.setFont(new java.awt.Font("Caladea", 1, 18)); // NOI18N
        jLabelTitle.setText("Authentification");

        jPasswordField.setText("root");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jTextFieldUsernameLogging, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jButtonLogging, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelEtatConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabelTitle)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsernameLogging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButtonLogging)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(jLabelEtatConnexion)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cette méthode permet l'authentification d'un utilisateur Elle appelle une
     * méthode de la classe BDDsql qui permet la connexion a la base de donnée
     */
    private void connexion() {

        String loginUsername = jTextFieldUsernameLogging.getText();
        String loginPassword = jPasswordField.getText();

        try {
            //bdd.connexionBdd();

            //Traitement
            if (bdd.connexion != null) {

                try ( //Création Statement pour requete / interaction base
                        Statement st = (Statement) bdd.connexion.createStatement()) {

                    String sql = ("SELECT * FROM profil WHERE username = '" + loginUsername + "' AND password = '" + loginPassword + "'");
                    ResultSet result = st.executeQuery(sql);

                    System.out.println(sql);
                    if (result.next()) {

                        JFrameAgent jfrm2 = new JFrameAgent();

                        jfrm2.setVisible(true);

                        String sqlPerm = ("SELECT * FROM profil WHERE permission = 1");
                        ResultSet resultPerm = st.executeQuery(sqlPerm);
                        if (resultPerm.next()) {

                            jfrm2.setTitle("Vous êtes authentifié en tant que Agent : " + loginUsername);
                        } else {
                            jfrm2.setTitle("Vous êtes authentifié en tant que Administrateur : " + loginUsername);
                        }

                        jTextFieldUsernameLogging.setEnabled(false);
                        jPasswordField.setEnabled(false);
                        jButtonLogging.setEnabled(false);
                        jLabelEtatConnexion.setText("Connecté avec : " + jTextFieldUsernameLogging.getText());

                        System.out.println("Authentification enabled, user was founded");
                    } else {
                        //JOptionPane.showMessageDialog(this, "Connexion échoué, utilisateur non existant !");
                        Object[] options = {"OK"};
                        System.out.println("Authentification Failed not user found");
                        JOptionPane.showOptionDialog(null, "Connexion échouée, utilisateur non trouvé !", "Erreur de connexion",
                                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                                null, options, options[0]);

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Formulaire.class.getName()).log(Level.SEVERE, null, ex);
                }
                bdd.connexion.close();

            }
        } catch (SQLException e) {

        }
    }


    private void jButtonLoggingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoggingActionPerformed

        this.connexion();
    }//GEN-LAST:event_jButtonLoggingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogging;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEtatConnexion;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsernameLogging;
    // End of variables declaration//GEN-END:variables

}
