/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ppe3;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author FIGUERES Adrien
 */
public class Formulaire extends javax.swing.JPanel {

    //Connection connexion;
    
    bddSQL bdd = new bddSQL();
    
    
    /**
     * Creates new form Formulaire
     */
    public Formulaire() {
        initComponents();
    }

        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldPasswordLogging = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsernameLogging = new javax.swing.JTextField();
        jButtonLogging = new javax.swing.JButton();
        jLabelEtatConnexion = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();

        jLabel1.setText("Username :");

        jTextFieldPasswordLogging.setText("root");

        jLabel2.setText("Password :");

        jTextFieldUsernameLogging.setText("Adriraxor");

        jButtonLogging.setText("Connexion");
        jButtonLogging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoggingActionPerformed(evt);
            }
        });

        jLabelEtatConnexion.setText("Non Connecter");

        jLabelTitle.setFont(new java.awt.Font("Caladea", 1, 18)); // NOI18N
        jLabelTitle.setText("Authentification");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEtatConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldPasswordLogging)
                                .addComponent(jTextFieldUsernameLogging, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(jButtonLogging, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabelTitle)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsernameLogging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPasswordLogging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addComponent(jButtonLogging)
                .addGap(35, 35, 35)
                .addComponent(jLabelEtatConnexion)
                .addContainerGap(204, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoggingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoggingActionPerformed
  
        String loginUsername = jTextFieldUsernameLogging.getText();
        String loginPassword = jTextFieldPasswordLogging.getText();
        
        try { 
            bdd.connexionBdd();
            
            //Traitement
            if(bdd.connexion != null) {
                
            try ( //Création Statement pour requete / interaction base
                    Statement st = (Statement) bdd.connexion.createStatement()) {
                //Traitement
                
                String sql = "SELECT * FROM profil WHERE username = '"+ loginUsername + "' AND password = '"+ loginPassword+"'";
                ResultSet result = st.executeQuery(sql);
                
                if(result.next()){
                    jLabelEtatConnexion.setText("Connexion Réussi : " + loginUsername);
                }else {
                    jLabelEtatConnexion.setText("Connexion échouée");
                } 
                }   catch (SQLException ex) {
                    Logger.getLogger(Formulaire.class.getName()).log(Level.SEVERE, null, ex);
                }
            bdd.connexion.close();
           
        }
        } catch (SQLException e){
            
        }
    }//GEN-LAST:event_jButtonLoggingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogging;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEtatConnexion;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextFieldPasswordLogging;
    private javax.swing.JTextField jTextFieldUsernameLogging;
    // End of variables declaration//GEN-END:variables
}
