/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ppe3;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FIGUERES Adrien
 */
public class JFrameAgent extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAgent
     */
    JTable table;

    public JFrameAgent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneOngletAgent = new javax.swing.JTabbedPane();
        jPanelClientConf = new javax.swing.JPanel();
        jButtonCreerClient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEmailClient = new javax.swing.JTextField();
        jTextFieldPrenomClient = new javax.swing.JTextField();
        jTextFieldTelClient = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomClient = new javax.swing.JTextField();
        jLabelEtatInsertionClient = new javax.swing.JLabel();
        jButtonAfficherClient = new javax.swing.JButton();
        jPanelCategorieProduit = new javax.swing.JPanel();
        jComboBoxCategories = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanelVenteProduit = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneOngletAgent.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPaneOngletAgent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneOngletAgentMouseClicked(evt);
            }
        });

        jButtonCreerClient.setText("Création du Client");
        jButtonCreerClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerClientActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom client : ");

        jLabel2.setText("Adresse email client : ");

        jLabel3.setText("numéro téléphone client : ");

        jTextFieldEmailClient.setText("Bernad.test@gmail.com");

        jTextFieldPrenomClient.setText("Bernard");

        jTextFieldTelClient.setText("0626248056");

        jLabel4.setText("Prenom client :");

        jTextFieldNomClient.setText("Test");

        jButtonAfficherClient.setText("Afficher Tous Les Clients");
        jButtonAfficherClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClientConfLayout = new javax.swing.GroupLayout(jPanelClientConf);
        jPanelClientConf.setLayout(jPanelClientConfLayout);
        jPanelClientConfLayout.setHorizontalGroup(
            jPanelClientConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientConfLayout.createSequentialGroup()
                .addGroup(jPanelClientConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientConfLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelClientConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelClientConfLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelClientConfLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPrenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelClientConfLayout.createSequentialGroup()
                                .addGroup(jPanelClientConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelClientConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelClientConfLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelEtatInsertionClient, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClientConfLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanelClientConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAfficherClient, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCreerClient, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelClientConfLayout.setVerticalGroup(
            jPanelClientConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientConfLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelClientConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPrenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClientConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClientConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClientConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTelClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButtonCreerClient)
                .addGap(18, 18, 18)
                .addComponent(jButtonAfficherClient)
                .addGap(180, 180, 180)
                .addComponent(jLabelEtatInsertionClient, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jTabbedPaneOngletAgent.addTab("Client Configuration", jPanelClientConf);

        jComboBoxCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriesActionPerformed(evt);
            }
        });

        jLabel5.setText("Filtre Produits");

        javax.swing.GroupLayout jPanelCategorieProduitLayout = new javax.swing.GroupLayout(jPanelCategorieProduit);
        jPanelCategorieProduit.setLayout(jPanelCategorieProduitLayout);
        jPanelCategorieProduitLayout.setHorizontalGroup(
            jPanelCategorieProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategorieProduitLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelCategorieProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(948, Short.MAX_VALUE))
        );
        jPanelCategorieProduitLayout.setVerticalGroup(
            jPanelCategorieProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategorieProduitLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addComponent(jComboBoxCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(490, Short.MAX_VALUE))
        );

        jTabbedPaneOngletAgent.addTab("Catégorie Produits", jPanelCategorieProduit);

        javax.swing.GroupLayout jPanelVenteProduitLayout = new javax.swing.GroupLayout(jPanelVenteProduit);
        jPanelVenteProduit.setLayout(jPanelVenteProduitLayout);
        jPanelVenteProduitLayout.setHorizontalGroup(
            jPanelVenteProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1192, Short.MAX_VALUE)
        );
        jPanelVenteProduitLayout.setVerticalGroup(
            jPanelVenteProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        jTabbedPaneOngletAgent.addTab("Vente Produit", jPanelVenteProduit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneOngletAgent)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneOngletAgent, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cette méthode nous permet de créer des clients Techniquement parlant nous
     * allons insérer nos clients dans notre table client via un INSERT INTO
     * client VALUES XXXXXXXXXXXXXXX
     */
    public void requeteInsertionClient() {

        BddSQL bdd = new BddSQL();
        bdd.connexionBdd();

        try {
            Statement requete = bdd.connexion.createStatement();
            String sql = ("INSERT INTO client (nom, prenom, Email, num_telephone) VALUES ('" + jTextFieldNomClient.getText() + "', '" + jTextFieldPrenomClient.getText() + "','" + jTextFieldEmailClient.getText() + "'," + jTextFieldTelClient.getText() + ")");
            requete.executeUpdate(sql);
            jLabelEtatInsertionClient.setText("Insertion Réussi du client : " + jTextFieldPrenomClient.getText() + "." + jTextFieldNomClient.getText());

        } catch (SQLException ex) {
            Logger.getLogger(BddSQL.class.getName()).log(Level.SEVERE, null, ex);
            jLabelEtatInsertionClient.setText("Insertion échoué du client !");
        }

    }

    /**
     * Méthode qui va nous permettre d'afficher la liste de tous les clients
     * appartenant à notre table client de notre base de donnée
     */
    public void afficherClient() {

        //Récupération connexion BDD, instanciation classe bddSQL
        BddSQL bdd = new BddSQL();
        bdd.connexionBdd();

        JFrameMain frm1 = new JFrameMain();
        //Configuration de la seconde JFrame qui va afficher notre liste de client
        JFrame frame2 = new JFrame("Liste des clients"); //Ce qui as dans la chaîne de caractère va définir le titre de la fenêtre

        frame2.setLayout(new FlowLayout());
        frame2.setSize(800, 800); //On définis la taille de la Frame

        //Configuration de notre JTable et du DefaultModel
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        table = new JTable(defaultTableModel);
        table.setPreferredScrollableViewportSize(new Dimension(600, 600));
        table.setFillsViewportHeight(true);
        frame2.add(new JScrollPane(table));

        //
        defaultTableModel.addColumn("idClient");
        defaultTableModel.addColumn("nomClient");
        defaultTableModel.addColumn("prenomClient");
        defaultTableModel.addColumn("Email");
        defaultTableModel.addColumn("num_telephone");

        try {

            Statement st = bdd.connexion.createStatement();//création de l'objet Statement
            String sql = "SELECT * FROM client";//Requete SQL qui va sélectionner tous nos champs
            ResultSet resultSet = st.executeQuery(sql);//Execution de notre requête SQL

            while (resultSet.next()) {

                //Récupération de nos tuples dans notre table client de notre base de donnée MySQL
                String id = resultSet.getString(1); //on récupère nos tuples du champs id
                String nom = resultSet.getString(2); //on récupère nos tuples du champs nom
                String prenom = resultSet.getString(3); //on récupère nos tuples du champs prenom
                String email = resultSet.getString(4); //on récupère nos tuples du champs Email
                String numTel = resultSet.getString(5); //on récupère nos tuples du champs num_telephone

                defaultTableModel.addRow(new Object[]{id, nom, prenom, email, numTel});//On ajoute nos tuples dans les lignes du tableau de notre Table Java
                frame2.setVisible(true);//On définis la visibilité de notre fenêtre sur TRUE (Ce qui permet de l'afficher)
                frame2.validate();

            }

        } catch (SQLException throwables) {
        }
    }

    /**
     * Cette méthode permet de choisir une catégorie et d'afficher les produits
     * lié à cette catégories
     */
    public void comboboxCategorie() {

        try {

            BddSQL bdd = new BddSQL();
            bdd.connexionBdd();

            Statement st = bdd.connexion.createStatement();
            ArrayList<String> catNames = new ArrayList<String>();
            ResultSet Rs = st.executeQuery("SELECT nom_categorie FROM categorie");

            while (Rs.next()) {
                String groupName = Rs.getString("nom_categorie");
                System.out.println(groupName);

                catNames.add(groupName);
                //Ajout des catégories dispo sur la comboBox
                //jComboBoxCategories.addItem(Rs.getString("nom_categorie"));
            }
            Rs.close();

            DefaultComboBoxModel model = new DefaultComboBoxModel(catNames.toArray());
            jComboBoxCategories.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameAgent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void jButtonCreerClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerClientActionPerformed
        // TODO add your handling code here:    
        this.requeteInsertionClient();
    }//GEN-LAST:event_jButtonCreerClientActionPerformed

    private void jButtonAfficherClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficherClientActionPerformed
        // TODO add your handling code here:
        this.afficherClient();
    }//GEN-LAST:event_jButtonAfficherClientActionPerformed

    private void jComboBoxCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriesActionPerformed
    }//GEN-LAST:event_jComboBoxCategoriesActionPerformed

    private void jTabbedPaneOngletAgentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneOngletAgentMouseClicked
        // TODO add your handling code here:
        this.comboboxCategorie();
    }//GEN-LAST:event_jTabbedPaneOngletAgentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAgent.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAgent.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAgent.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAgent.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAfficherClient;
    private javax.swing.JButton jButtonCreerClient;
    private javax.swing.JComboBox<String> jComboBoxCategories;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelEtatInsertionClient;
    private javax.swing.JPanel jPanelCategorieProduit;
    private javax.swing.JPanel jPanelClientConf;
    private javax.swing.JPanel jPanelVenteProduit;
    private javax.swing.JTabbedPane jTabbedPaneOngletAgent;
    private javax.swing.JTextField jTextFieldEmailClient;
    private javax.swing.JTextField jTextFieldNomClient;
    private javax.swing.JTextField jTextFieldPrenomClient;
    private javax.swing.JTextField jTextFieldTelClient;
    // End of variables declaration//GEN-END:variables
}
