/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ppe3;

import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FIGUERES Adrien
 */
public class JFrameAdmin extends javax.swing.JFrame {

    JTable tablePrd;

    /**
     * Creates new form JFrameAdmin
     */
    public JFrameAdmin() {
        initComponents();
        this.afficherProduit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAjouterProduit = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescriptionProduit = new javax.swing.JTextArea();
        jTextFieldStockProduit = new javax.swing.JTextField();
        jTextFieldNomProduit = new javax.swing.JTextField();
        jTextFieldTarifProduit = new javax.swing.JTextField();
        jFileChooserProduit = new javax.swing.JFileChooser();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPaneAdmin = new javax.swing.JTabbedPane();
        jPanelGestioCatProduit = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListeProduit = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonUpdateProduit = new javax.swing.JButton();
        jButtonDelProduit = new javax.swing.JButton();
        jButtonAddProduit = new javax.swing.JButton();
        jPanelGestionClient = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelGestionVente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelStatVente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelFacture = new javax.swing.JPanel();

        jLabel2.setText("Nom Produit : ");

        jLabel5.setText("Tarif Produit : ");

        jLabel6.setText("Stock Produit : ");

        jLabel7.setText("Description du produit : ");

        jLabel8.setText("Insérez une image/photo du produit : ");

        jTextAreaDescriptionProduit.setColumns(20);
        jTextAreaDescriptionProduit.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescriptionProduit);

        jLabel9.setText("Ajout d'un produit");

        javax.swing.GroupLayout jDialogAjouterProduitLayout = new javax.swing.GroupLayout(jDialogAjouterProduit.getContentPane());
        jDialogAjouterProduit.getContentPane().setLayout(jDialogAjouterProduitLayout);
        jDialogAjouterProduitLayout.setHorizontalGroup(
            jDialogAjouterProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAjouterProduitLayout.createSequentialGroup()
                .addGroup(jDialogAjouterProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAjouterProduitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDialogAjouterProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogAjouterProduitLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(jDialogAjouterProduitLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldStockProduit))
                            .addGroup(jDialogAjouterProduitLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jDialogAjouterProduitLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(5, 5, 5)
                                .addComponent(jTextFieldNomProduit))
                            .addGroup(jDialogAjouterProduitLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTarifProduit))))
                    .addGroup(jDialogAjouterProduitLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jFileChooserProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAjouterProduitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
        );
        jDialogAjouterProduitLayout.setVerticalGroup(
            jDialogAjouterProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAjouterProduitLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialogAjouterProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAjouterProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTarifProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAjouterProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldStockProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAjouterProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jFileChooserProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneAdmin.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        jTableListeProduit.setModel(new DefaultTableModel());
        jScrollPane1.setViewportView(jTableListeProduit);

        jButtonUpdateProduit.setText("Modifier un Produit");
        jButtonUpdateProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateProduitActionPerformed(evt);
            }
        });

        jButtonDelProduit.setText("Supprimer un Produit");
        jButtonDelProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelProduitActionPerformed(evt);
            }
        });

        jButtonAddProduit.setText("Ajouter un Produit");
        jButtonAddProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProduitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDelProduit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUpdateProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonAddProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDelProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdateProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGestioCatProduitLayout = new javax.swing.GroupLayout(jPanelGestioCatProduit);
        jPanelGestioCatProduit.setLayout(jPanelGestioCatProduitLayout);
        jPanelGestioCatProduitLayout.setHorizontalGroup(
            jPanelGestioCatProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGestioCatProduitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelGestioCatProduitLayout.setVerticalGroup(
            jPanelGestioCatProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGestioCatProduitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Gestion Produit et Catégorie", jPanelGestioCatProduit);

        jLabel1.setText("Modifier Client (id nom prenom etc...)");

        javax.swing.GroupLayout jPanelGestionClientLayout = new javax.swing.GroupLayout(jPanelGestionClient);
        jPanelGestionClient.setLayout(jPanelGestionClientLayout);
        jPanelGestionClientLayout.setHorizontalGroup(
            jPanelGestionClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionClientLayout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        jPanelGestionClientLayout.setVerticalGroup(
            jPanelGestionClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionClientLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        jTabbedPaneAdmin.addTab("Gestion des clients", jPanelGestionClient);

        jLabel3.setText("Afficher vente effectuer par un agent à un client");

        javax.swing.GroupLayout jPanelGestionVenteLayout = new javax.swing.GroupLayout(jPanelGestionVente);
        jPanelGestionVente.setLayout(jPanelGestionVenteLayout);
        jPanelGestionVenteLayout.setHorizontalGroup(
            jPanelGestionVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionVenteLayout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        jPanelGestionVenteLayout.setVerticalGroup(
            jPanelGestionVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionVenteLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        jTabbedPaneAdmin.addTab("Gestion des ventes", jPanelGestionVente);

        jLabel4.setText("Produit nombre de fois vendus");

        javax.swing.GroupLayout jPanelStatVenteLayout = new javax.swing.GroupLayout(jPanelStatVente);
        jPanelStatVente.setLayout(jPanelStatVenteLayout);
        jPanelStatVenteLayout.setHorizontalGroup(
            jPanelStatVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatVenteLayout.createSequentialGroup()
                .addContainerGap(403, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(385, 385, 385))
        );
        jPanelStatVenteLayout.setVerticalGroup(
            jPanelStatVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatVenteLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jTabbedPaneAdmin.addTab("Statistique vente", jPanelStatVente);

        javax.swing.GroupLayout jPanelFactureLayout = new javax.swing.GroupLayout(jPanelFacture);
        jPanelFacture.setLayout(jPanelFactureLayout);
        jPanelFactureLayout.setHorizontalGroup(
            jPanelFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1188, Short.MAX_VALUE)
        );
        jPanelFactureLayout.setVerticalGroup(
            jPanelFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        jTabbedPaneAdmin.addTab("Generer Facture", jPanelFacture);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneAdmin)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAdmin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProduitActionPerformed
        // TODO add your handling code here:
        //**jDialog (lors du clique sur le bouton cela va afficher une fenêtre dans lequel la modification d'un client pourras être effectué
        jDialogAjouterProduit.setVisible(true); //On définis la jDialog sur une visibilité de type "Vraie" c'est à dire que l'on rend visible la fenêtre jDialog
        jDialogAjouterProduit.setSize(1000, 1000); //On définis les dimensions de la jDialog
        jDialogAjouterProduit.setResizable(false); //On interdit le redimensionnement de la fenêtre jDialog
        jDialogAjouterProduit.setLocationRelativeTo(this); //On centre la fenêtre lors de l'ouverture 
    }//GEN-LAST:event_jButtonAddProduitActionPerformed

    private void jButtonDelProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDelProduitActionPerformed

    private void jButtonUpdateProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateProduitActionPerformed

    /**
     * Méthode qui permete d'afficher tous les produits
     */
    public void afficherProduit() {
        //Etape de connexion temporaire à notre base de données (Modification future avec DaoSIO
        DaoSIO.getInstance();

        //Création de l'objet de type DefaultTableModel qui sera lié à notre jTable des clients
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        tablePrd = new JTable(defaultTableModel);
        tablePrd.setPreferredScrollableViewportSize(new Dimension(600, 600));
        tablePrd.setFillsViewportHeight(true);

        //Ajout des colonnes à notre jTable
        defaultTableModel.addColumn("idProduit");
        defaultTableModel.addColumn("nom produit");
        defaultTableModel.addColumn("tarif produit");
        defaultTableModel.addColumn("stock produit");
        defaultTableModel.addColumn("description produit");
        defaultTableModel.addColumn("photo produit");
        defaultTableModel.addColumn("Popularite / Evaluation");
        try {

            ResultSet resultSet = DaoSIO.getInstance().requeteSelection("SELECT * FROM produit"); //Selection, Récupération de tous nos clients issus de notre base de données SQL de la table client 

            while (resultSet.next()) {

                //Récupération de nos tuples dans notre table client de notre base de donnée MySQL
                String idPrd = resultSet.getString(1); //on récupère nos tuples du champs idProduit
                String nomPrd = resultSet.getString(2); //on récupère nos tuples du champs nomProduit
                String tarifPrd = resultSet.getString(3); //on récupère nos tuples du champs tarifProduit
                String stockPrd = resultSet.getString(4); //on récupère nos tuples du champs stockProduit
                String descPrd = resultSet.getString(5); //on récupère nos tuples du champs descriptionProduit
                String photoPrd = resultSet.getString(6); //on récupère nos tuples du champs photo Produit
                String evaluationPrd = resultSet.getString(5); //on récupère nos tuples du champs evaluation Produit

                defaultTableModel.addRow(new Object[]{idPrd, nomPrd, tarifPrd, stockPrd, descPrd, photoPrd, evaluationPrd});//On ajoute nos tuples dans les lignes du tableau de notre Table Java
            }
            jTableListeProduit.setModel(defaultTableModel);
        } catch (SQLException throwables) {
        }
    }

    /**
     * Methode qui permet d'ajouter un produit
     */
    public void ajoutProduit() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddProduit;
    private javax.swing.JButton jButtonDelProduit;
    private javax.swing.JButton jButtonUpdateProduit;
    private javax.swing.JDialog jDialogAjouterProduit;
    private javax.swing.JFileChooser jFileChooserProduit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFacture;
    private javax.swing.JPanel jPanelGestioCatProduit;
    private javax.swing.JPanel jPanelGestionClient;
    private javax.swing.JPanel jPanelGestionVente;
    private javax.swing.JPanel jPanelStatVente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneAdmin;
    private javax.swing.JTable jTableListeProduit;
    private javax.swing.JTextArea jTextAreaDescriptionProduit;
    private javax.swing.JTextField jTextFieldNomProduit;
    private javax.swing.JTextField jTextFieldStockProduit;
    private javax.swing.JTextField jTextFieldTarifProduit;
    // End of variables declaration//GEN-END:variables
}
